Import ('env')

env.Append(CXXFLAGS=['--std=c++0x'])

name = 'acuoso'
inc = env.Dir('.')
src = env.Glob('*.cpp')
deps = ['etilico', 'mili', 'biopp', 'gtest_main', 'gtest']

env.CreateTest(name, inc, src, deps)