Import ('env')

name = 'acuoso'
inc = env.Dir('.'), env.Dir('../../etilico')
src = env.Glob('*.cpp')
deps = ['acuoso', 'etilico', 'mili', 'biopp', 'gtest_main', 'gtest']

env.CreateTest(name, inc, src, deps)